Require Import Coq.ZArith.Zdiv.
Require Import Coq.ZArith.ZArith.
Require Import Coq.ZArith.Znumtheory.
Require Import Lia.
Require Import Recdef.
Require Import Bool.




Open Scope Z_scope.


     

(*Now we prove that primitive root construction is indeed injective
 (i.e., {p^0,...,p^{p-2} are all distinct.})*)
Definition coprime (a b: Z) :Prop := Z.gcd a b = 1.


Definition primitive_root (g p : Z) : Prop :=
    prime p /\
    coprime g p /\
    forall a : Z, 1 <= a < p -> coprime a p ->
    exists i : Z, 0 <= i < p - 1/\ ((g ^ i) mod p) = a.


(*
  For order, we avoid to give a real definition, since that would 
  require extra contruction on cardinality, generator, groups, orbit, 
  etc. 
  
  We just give the definition for this specific case, where order of g 
  in the multiplicative opeartion of mod p (in (Z/pZ)x) is exactly p - 1.
  *)
Definition order_eq_pminus1 (g p : Z) : Prop :=
  g ^ (p - 1) mod p = 1 /\
  forall k : Z, 0 < k -> k < p - 1 -> g ^ k mod p <> 1.

Theorem primitive_root_order_eq :
  forall g p : Z,
  primitive_root g p ->
  order_eq_pminus1 g p.
Proof.
  (* For simplicity, I give a handwavy proof
    because this requires some construction on group, cardinality, generator, etc.
  
    Let G = (Z/pZ)×, the multiplicative group modulo prime p (without 0).
    By the definition of primitive root, 
      g^i where 0 < i <= p - 1, and for every 1 <= a <= p-1 exists some i such that
      g^i = a.
    Then the group, generated by g (denoted as <g>), must be exactly (Z/pZ)x.
    Now we know |(Z/pZ)×| = p - 1 by counting.
    And ord(g) = |<g>| = |(Z/pZ)×| = p - 1.

    Mathcomp
*)
Admitted.




(*SHOULD HAVE USED pos_div_eucl, BUT WE ARE TOO LATE*)
Theorem Euclidean_division_mod :
  forall r p q s: Z, r > 0 ->
  p > 1 ->
  Z.div_eucl r (p - 1) = (q, s) ->
   s = s mod (p - 1).
Proof.
  intros r p q s Hr Hp Hdiv.

  (* Cast r to positive *)
  assert (Hr_pos : 0 < r) by lia.
  set (r_pos := Z.to_pos r).  (* r as type positive *)

  (* Cast p-1 to N, show it's <> 0%N *)
  assert (Hp1 : 0 < p - 1) by lia.
  set (pm1_N := Z.to_N (p - 1)).  (* p-1 as type N *)
  assert (Hpm1_ne : pm1_N <> 0%N).
  { unfold pm1_N. zify. lia. }

  (* Use mod_pos_bound to get s < p-1 *)
  assert (Hs_bound : s < p - 1).
  {
    assert (Hpos : 0 < p - 1) by lia.
    pose proof (Z.div_eucl_eq r (p - 1)) as Heq.
    pose proof (Z.mod_pos_bound r (p - 1) Hpos) as Hbound.
    unfold Z.modulo in Hbound.
    rewrite Hdiv in Hbound.
    simpl in Hbound.
    lia.
  }

  (* Get s >= 0 from mod_pos_bound *)
  assert (Hs_pos : 0 <= s).
  {
    assert (Hpos : 0 < p - 1) by lia.
    pose proof (Z.mod_pos_bound r (p - 1) Hpos) as Hbound.
    unfold Z.modulo in Hbound.
    rewrite Hdiv in Hbound.
    simpl in Hbound.
    lia.
  }

  (* Apply Z.mod_small *)
  symmetry.
  apply Z.mod_small.
  lia.
Qed.

Lemma Euclidean_division_pos:
  forall r p q s: Z, r > 0 ->
  p > 1 ->
  Z.div_eucl r (p - 1) = (q, s) ->
  0 <= q.
Proof.
  intros r p q s Hr Hp Hdiv.
  assert (Hpos :0 < p - 1) by lia.
  assert (Hrge : 0 <= r) by lia.
  pose proof (Z.div_pos r (p - 1) Hrge Hpos) as Hq.
  unfold Z.div in Hq.
  rewrite Hdiv in Hq.
  simpl in Hq.
  assumption.
Qed.


Lemma mod_cancel : forall p a b c,
  prime p ->
  c mod p <> 0 ->
  (a * c) mod p = (b * c) mod p ->
  a mod p = b mod p.
Proof. Admitted. (*Alreadt proven before.*)

Lemma primitive_root_coprime :
  forall g p : Z,
  primitive_root g p ->
  Z.gcd g p = 1.
Proof. intros. unfold primitive_root in H. destruct H. destruct H0.
    apply H0.
Qed.


(*rel_prime_mult:
forall a b c : Z,
rel_prime a b -> rel_prime a c -> rel_prime a (b * c)
Zgcd_1_rel_prime:
forall a b : Z, Z.gcd a b = 1 <-> rel_prime a b
*)

Lemma coprime_pow :
  forall g p k : Z,
  coprime g p ->
  0 <= k ->
  coprime (g ^ k) p.
Proof.
  intros.
  unfold coprime in *.
  apply Zgcd_1_rel_prime.
  apply Zgcd_1_rel_prime in H.
  (* convert to nat induction *)
  rewrite <- (Z2Nat.id k H0).
  generalize (Z.to_nat k) as n.
  induction n as [| n IHn].
  - simpl. apply rel_prime_1.
  - rewrite Nat2Z.inj_succ.
  rewrite Z.pow_succ_r by lia.
  apply rel_prime_sym.
  eapply rel_prime_mult.
  + apply rel_prime_sym. assumption.
  + apply rel_prime_sym. apply IHn.
Qed.


Search "div_eucl".
(*Z.pow_mul_l: forall a b c : Z, (a * b) ^ c = a ^ c *
b ^ c
Z.pow_add_r: forall a b c : Z,
0 <= b -> 0 <= c -> a ^ (b + c) = a ^ b * a ^ c

Ndiv_def.Pdiv_eucl_remainder:
forall a b : positive,
(snd (Ndiv_def.Pdiv_eucl a b) < N.pos b)%N*)

Lemma pow_split :
  forall g m k : Z,
  0 <= m /\ 0 <= k ->
  m >= k ->
  g ^ m = g ^ (m - k) * g ^ k.
Proof. intros.  destruct H. 
    replace m with (m - k + k) by lia. rewrite Z.pow_add_r; try (lia).
    replace (m - k + k - k) with (m - k).
    reflexivity. lia.
Qed.
    



(*Zmult_mod_idemp_l:
forall a b n : Z, (a mod n * b) mod n = (a * b) mod n

Z.mul_nonpos_nonneg:
forall n m : Z, n <= 0 -> 0 <= m -> n * m <= 0


Z.mod_pow_l: forall a b c : Z,
(a mod c) ^ b mod c = a ^ b mod c*)


Lemma order_divides :
  forall g p r : Z,
  primitive_root g p ->
  order_eq_pminus1 g p ->
  r > 0 ->
  g ^ r mod p = 1 ->
  ((p - 1) | r)%Z.
Proof.
  intros g p r Hprim Hord Hr Hgr.
  unfold order_eq_pminus1 in Hord.
  destruct Hord as [Hfull Hmin].

  (* Write r = (p-1)q + s by Euclidean division *)
  destruct (Z.div_eucl r (p - 1)) as [q s] eqn:Hdiv.

  assert (Hpbound : p - 1 > 0).
  { unfold primitive_root in Hprim.
    destruct Hprim as [Hprime _].
    apply Z.lt_gt.
    apply prime_ge_2 in Hprime.
    lia. }

  assert (Hlt : 0 < p - 1) by lia.
  assert (Hne : p - 1 <> 0) by lia.

  assert (Heucl := Z.div_eucl_eq r (p - 1)).
  rewrite Hdiv in Heucl.
  specialize (Heucl Hne).
  (* Heucl : r = (p - 1) * q + s *)

  assert (Hbound : 0 <= r mod (p - 1) < p - 1).
  { apply Z.mod_pos_bound. exact Hlt. }

  assert (Hs : s = r mod (p - 1)).
  { rewrite Heucl. rewrite Z.add_comm. rewrite Z.mul_comm. 
  rewrite Z.mod_add; try lia.
  apply Euclidean_division_mod with (r := r) (q := q).
  - assumption.
  - unfold primitive_root in Hprim. destruct Hprim. apply prime_ge_2 in H.
  lia.
  - assumption. 
  }

  assert (Hsbound : 0 <= s < p - 1).
  { rewrite Hs. exact Hbound. }

  assert (Hqnonneg : 0 <= q).
  { destruct Hsbound as [Hslo _].
  apply Euclidean_division_pos with (r := r) (p := p) (s := s); try (assumption).
  unfold primitive_root in Hprim. destruct Hprim. apply prime_ge_2 in H.
  lia.

  
  }

  assert (Hpow : (g ^ (p - 1)) ^ q mod p = 1).
{ rewrite <- Z.mod_pow_l.
  rewrite Hfull.
  rewrite Z.pow_1_l; try lia.
  apply Z.mod_1_l.
  unfold primitive_root in Hprim.
  destruct Hprim as [Hprime _].
  apply prime_ge_2 in Hprime. lia. }


  assert (Hrsplit : g ^ r = (g ^ (p - 1)) ^ q * g ^ s).
    { rewrite Heucl.
      rewrite Z.pow_add_r; try lia.
      rewrite Z.pow_mul_r; try lia.
      apply Z.mul_nonneg_nonneg; lia.
    }
  (* Show g^s ≡ 1 (mod p) *)
  assert (Hgs : g ^ s mod p = 1).
  {
    rewrite Hrsplit in Hgr.
    rewrite Z.mul_mod in Hgr; try lia.
    rewrite Hpow in Hgr.
    rewrite Z.mul_1_l in Hgr.

    rewrite Z.mod_mod in Hgr.
    - assumption.
    - unfold primitive_root in Hprim.
      destruct Hprim as [Hprime _].
      apply prime_ge_2 in Hprime. lia.
    }

  (* Since 0 <= s < p-1 and g^s ≡ 1, minimality forces s = 0 *)
  assert (Hs0 : s = 0).
  { destruct (Z.eq_dec s 0) as [Hs0 | Hs0].
    - exact Hs0.
    - exfalso.
      destruct Hsbound as [Hslo Hshi].
      assert (Hspos : 0 < s) by lia.
      exact (Hmin s Hspos Hshi Hgs).
  }

  exists q.
  rewrite Heucl.
  lia.
Qed.
      

Search "mul_pos".


Lemma mod_zero_gcd :
  forall a p : Z,
  prime p ->
  a mod p = 0 ->
  Z.gcd a p = p.

Proof. intros a p Hprime Hmod.
  apply Z.mod_divide in Hmod; [| apply prime_ge_2 in Hprime; lia].
  (* gcd(a, p) divides p, and p is prime, so gcd = 1 or gcd = p *)
  (* Since p | a, we have p | gcd(a, p), so gcd = p *)
  apply Z.gcd_unique.
  - apply prime_ge_2 in Hprime; lia.
  - assumption.
  - apply Z.divide_refl.
  - intros.
  apply H0.
Qed.

(*Z.mod_1_l: forall a : Z, 1 < a -> 1 mod a = 1*)

Lemma primitive_root_injective_aux :
  forall g p m k : Z,
  primitive_root g p ->
  0 <= m < p - 1 ->
  0 <= k < p - 1 ->
  g ^ m mod p = g ^ k mod p ->
  k < m ->
  False.
Proof. intros g p m k H H0 H1 H2 Hlt.
assert (H3 : g ^ m = g ^ (m - k) * g ^ k).
{ apply pow_split. lia. lia. }
rewrite H3 in H2. 
assert (H4 : g^(m - k) mod p = 1 mod p).
{ destruct H as [Hp [Hcp Hpr]].
  apply mod_cancel with (c := g^k).
  + assumption.
  + intros Hcontra. assert (Hcpk : coprime (g ^ k) p).
    { apply coprime_pow.
      + assumption.
      + lia. }
    unfold coprime in Hcpk. apply mod_zero_gcd in Hcontra. 
    - lia.
    - assumption. 
  + replace (1*g ^k ) with (g^k).
    - assumption.
    - lia. }
assert (H5 : ((p - 1) | m - k)%Z).
{ apply order_divides with (g:=g).
  + apply H.
  + apply primitive_root_order_eq. apply H.
  + replace (1 mod p) with 1 in H4. lia. symmetry. apply Z.mod_1_l. unfold primitive_root in H. destruct H as [Hprime _].
    apply prime_ge_2 in Hprime. lia.
  +  replace (1 mod p) with 1 in H4. lia. symmetry. apply Z.mod_1_l. unfold primitive_root in H. destruct H as [Hprime _].
    apply prime_ge_2 in Hprime. lia. }
assert (H6 : m - k = 0).
{ unfold Z.divide in H5.
  destruct H5 as [n Hn].
  assert (Hpge2 : p - 1 >= 1).
  { unfold primitive_root in H. destruct H as [Hprime _].
    apply prime_ge_2 in Hprime. lia. }
  (* m - k >= 0 from Hlt, and m - k < p - 1 from H0, H1 *)
  assert (Hmk_bound : 0 <= m - k < p - 1) by lia.
  rewrite Hn in Hmk_bound.
  apply primitive_root_order_eq in H. unfold order_eq_pminus1 in H.
  destruct H as [Hord Hmin].
  destruct (Z.eq_dec (m - k) 0) as [Heq | Hne].
  - exact Heq.
  - exfalso.
    assert (Hpos : 0 < m - k) by lia.
    apply (Hmin (m - k)).
    + lia.
    + lia.
    + rewrite H4. apply Z.mod_1_l. lia. }
lia.
Qed.

Theorem primitive_root_injective :
  forall g p m k : Z,
  primitive_root g p ->
  0 <= m < p - 1 ->
  0 <= k < p - 1 ->
  g ^ m mod p = g ^ k mod p ->
  m = k.
  Proof. intros. 
    destruct (Z.lt_trichotomy k m) as [Hlt | [Heq | Hgt]].
    - assert (False).
    {
      apply primitive_root_injective_aux with (g := g) (p := p) (m := m)(k := k);
      try (assumption).

    }
    lia.
    - lia.
    - assert (False).
    {
      apply primitive_root_injective_aux with (g := g) (p := p) (m := k)(k := m);
      try (assumption). symmetry. assumption.
    }
    lia.
  Qed.

  (* Assuming k <= m does not lose generality.*)

